name: Arma 3 Wasteland
tagline: Turning Altis into the ultimate competative sandbox

repo: https://github.com/A3Wasteland/ArmA3_Wasteland.Altis

markdown: redcarpet
pygments: true
author:
  name: Team Wasteland
  email: team@a3wasteland.com
  github: https://github.com/A3Wasteland/ArmA3_Wasteland.Altis

